//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DOAN_Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API_DOAN_Core.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi..
        /// </summary>
        internal static string Exception_DevMsg {
            get {
                return ResourceManager.GetString("Exception_DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khóa học đã tồn tại..
        /// </summary>
        internal static string Exception_Error_CourseCode {
            get {
                return ResourceManager.GetString("Exception_Error_CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khóa học chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_CourseCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_CourseCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bài học đã tồn tại..
        /// </summary>
        internal static string Exception_Error_LessonCode {
            get {
                return ResourceManager.GetString("Exception_Error_LessonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bài học chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_LessonCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_LessonCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bản tin chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_NewCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_NewCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bản tin đã tồn tại..
        /// </summary>
        internal static string Exception_Error_NewCode_Yes {
            get {
                return ResourceManager.GetString("Exception_Error_NewCode_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã câu hỏi đã tồn tại..
        /// </summary>
        internal static string Exception_Error_QuestionCode {
            get {
                return ResourceManager.GetString("Exception_Error_QuestionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã câu hỏi chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_QuestionCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_QuestionCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bài nhạc đã tồn tại..
        /// </summary>
        internal static string Exception_Error_RadioCode {
            get {
                return ResourceManager.GetString("Exception_Error_RadioCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bài nhạc chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_RadioCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_RadioCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người dùng đã tồn tại..
        /// </summary>
        internal static string Exception_Error_UserCode {
            get {
                return ResourceManager.GetString("Exception_Error_UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã người dùng chưa tồn tại..
        /// </summary>
        internal static string Exception_Error_UserCode_No {
            get {
                return ResourceManager.GetString("Exception_Error_UserCode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại người dùng không hợp lệ..
        /// </summary>
        internal static string Exception_Error_UserType {
            get {
                return ResourceManager.GetString("Exception_Error_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã video đã tồn tại..
        /// </summary>
        internal static string Exception_Error_VideoCode {
            get {
                return ResourceManager.GetString("Exception_Error_VideoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video này đã tồn tại..
        /// </summary>
        internal static string Exception_Error_VideoObject {
            get {
                return ResourceManager.GetString("Exception_Error_VideoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi, vui lòng liên hệ với người quản trị..
        /// </summary>
        internal static string Exception_UserMsg {
            get {
                return ResourceManager.GetString("Exception_UserMsg", resourceCulture);
            }
        }
    }
}
